language: android

node_js:
  - 5.5
jdk:
  - oraclejdk8


notifications:
  slack: openfoodfacts:pRddUFWA1nqbJ03sffyEzo18

sudo: false

branches:
  only:
  - master

install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade -y oracle-java8-installer
  - npm cache clean
  - npm install
  - npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
  - exit 0  
