language: android

node_js:
  - 5.5

notifications:
  slack: openfoodfacts:pRddUFWA1nqbJ03sffyEzo18

sudo: false

branches:
  only:
  - master

install:
  - export JAVA_HOME=/Library/java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
  - export PATH=$JAVA_HOME/bin:$PATH
  - export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
  - npm cache clean
  - npm install
  - npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-23

before_script:
  - cordova platform rm android
  - cordova platform add android

script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
  - exit 0  
